#!/usr/bin/env bash
# Install ufw and configure it to block all incoming traffic except SSH, HTTP, and HTTPS

sudo apt-get update
sudo apt-get install -y ufw
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable
