#!/usr/bin/env bash
# Installs Nginx and configures a custom X-Served-By header with the server's hostname

apt-get -y update
apt-get -y install nginx

echo "Holberton School for the win!" > /var/www/html/index.html

# shellcheck disable=SC2154
sed -i '/server_name _;/a\        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx start
service nginx restart
