#!/usr/bin/env bash
# Installs and configures HAProxy to load balance traffic across web-01 and web-02
apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

cat >> /etc/haproxy/haproxy.cfg << EOF

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 3.86.165.61:80 check
    server web-02 3.80.148.172:80 check
EOF

service haproxy restart
