#!/usr/bin/env bash
# Installs and configures Nginx to serve a default page containing "Holberton School"

apt-get -y update
apt-get -y install nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx start
service nginx restart
