#!/usr/bin/env bash
# Configures Nginx to serve a default page and redirect /redirect_me to another URL

apt-get -y update
apt-get -y install nginx

echo "Holberton School for the win!" > /var/www/html/index.html

sed -i '/server_name _;/a\        location /redirect_me {\n                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }' /etc/nginx/sites-available/default

service nginx start
service nginx restart
