#!/usr/bin/env bash
# Installs nginx and configures a custom 404 page with a specific message
apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/listen 80 default_server/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/listen 80 default_server/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx start
