#!/usr/bin/env bash
# Configures Nginx with default page, /redirect_me redirect, and custom 404 page

apt-get -y update
apt-get -y install nginx

echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a\        location /redirect_me {\n                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }\n        error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx start
service nginx restart
